-- AlterTable
ALTER TABLE "Invitation" ALTER COLUMN "startDate" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "endDate" SET DATA TYPE TIMESTAMPTZ(3);

-- AlterTable
ALTER TABLE "Invitee" ALTER COLUMN "respondedAt" SET DATA TYPE TIMESTAMPTZ(3);
